<?php
defined('BASEPATH') or exit('No direct script access allowed');
/* * ************************************************************
 *  File: summery.php
 *  Path: application/views/blocks/contact/summery.php
 *  Description: It's a homepage Text box for add group.
 *  
 *  History:
 *  Programmer          Date                    Description
 *  -----------         ----------              ----------------
 *  Rahul Siwal         30/05/2021              Created
 *
 */
$domain_name = $this->config->item("domain_name");
?>
<div class="row pt-4 pb-4">
    <div class="container">
        <div class="row">
            <div class="col-12 m-auto">
                <div>
                    <h1>Terms of Service</h1>
                </div>
                <p><strong>We are not associated with WhatsApp messenger by any means. WhatsApp is a registered trademark of WhatsApp Inc.</strong></p>
                <div>
                    <dl>
                        <dt><label>Acceptance of Terms</label></dt>
                        <dd>By accessing, linking to, or using this website you confirm your acceptance of these Terms and Conditions, which may be updated by us from time to time with or without notice to you. Your access or use of the services in this website signifies that you agree to become bound by these Terms and Conditions. If you do not agree to all the Terms, then you are not permitted to access or use the content or any service on the website. While joining the group you agree that any conversation in the group or carried out personally is through your sole discretion and <?= $domain_name; ?> does not hold any responsibility for the conversation or any outcome of the conversation.</dd>
                        <dt><label>Description of Service</label></dt>
                        <dd><strong><?= $domain_name; ?></strong> currently provides users with certain services and content, as described more fully on the site, (the &quot;Services&quot;). You also understand and agree that&nbsp;<strong><?= $domain_name; ?></strong> assumes no responsibility for the suitability, reliability, availability, timeliness, and accuracy of the information and services contained within&nbsp;<strong><?= $domain_name; ?></strong> website for any purpose. Services are provided &quot;AS IS&quot; without a warranty of any kind.</dd>
                        <dt><label>Modification of Service</label></dt>
                        <dd><strong><?= $domain_name; ?></strong> reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice to you. You agree that&nbsp;<strong><?= $domain_name; ?></strong> shall not be liable to you or to any third party for any modification, suspension, or discontinuance of the Service.</dd>
                        <dt><label>Registration Obligations</label></dt>
                        <dd>You are not required to register with&nbsp;<strong><?= $domain_name; ?></strong> before using the services, but you understand that certain features of the Service may not be accessible to you unless you register. In registering for the service you agree to provide&nbsp;<strong><?= $domain_name; ?></strong> with true, accurate, and complete registration information.&nbsp;<strong><?= $domain_name; ?></strong> reserves the right to suspend or terminate your account and refuse any and all current or future use of the Service (or any portion thereof), with or without notice to you. Services are available only to individuals who are at least 13 years old. Any use of or access to the website by anyone under 13 years of age is unauthorized and in violation of these Terms and conditions.</dd>
                        <dt><label>Privacy policy</label></dt>
                        <dd>You may review&nbsp;<strong><?= $domain_name; ?></strong> privacy policy here:&nbsp;<a href="<?= url("privacy"); ?>"><strong><u>Privacy Policy</u></strong></a></dd>
                        <dt><label>User Conduct</label></dt>
                        <dd>You understands that all information, data, text, software, music, sound, photographs, graphics, video, messages, or other materials (&quot;Content&quot;), whether publicly posted or privately transmitted, are the sole responsibility of the person from which such Content originated. This means that you, and not&nbsp;<strong><?= $domain_name; ?></strong>, are entirely responsible for all Content that you upload, post, email, transmit or otherwise make available via the Service.&nbsp;<strong><?= $domain_name; ?></strong> does not control the Content posted via the Service and, as such, does not guarantee the accuracy, integrity, or quality of such Content. You understand that by using the Service, you may be exposed to Content that is offensive, indecent, or objectionable. Under no circumstances will&nbsp;<strong><?= $domain_name; ?></strong> be liable in any way for any Content, including, but not limited to, for any errors or omissions in any Content, or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available via the Service. You agree to not use the Service to:<p>(a) link to, upload, post, email, transmit or otherwise make available any Content that is adult in nature, unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another&apos;s privacy, hateful, or racially, ethnically or otherwise objectionable;</p>
                            <p>(b) harm minors in any way;</p>
                            <p>(c) impersonate any person or entity, including, but not limited to, a&nbsp;<strong><?= $domain_name; ?></strong> official, guide or host, or falsely state or otherwise misrepresent your affiliation with a person or entity;</p>
                            <p>(d) forge headers or otherwise manipulate identifiers in order to disguise the origin of any content transmitted through the Service;</p>
                            <p>(e) link, upload, post, email, transmit or otherwise make available any content that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</p>
                            <p>(f) link, upload, post, email, transmit or otherwise make available any content that infringes any patent, trademark, trade secret, copyright, or other proprietary rights (&quot;Rights&quot;) of any party;</p>
                            <p>(g) link, upload, post, email, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, &quot;junk mail,&quot; &quot;spam,&quot; &quot;chain letters,&quot; &quot;pyramid schemes,&quot; or any other form of solicitation, except in those areas (such as shopping rooms) that are designated for such purpose (please read our complete Spam Policy);</p>
                            <p>(h) link, upload, post, email, transmit or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</p>
                            <p>(i) disrupt the normal flow of dialogue, cause a screen to &quot;scroll&quot; faster than other users of the Service are able to type, or otherwise act in a manner that negatively affects other users&apos; ability to engage in real-time exchanges;</p>
                            <p>(j) interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service;</p>
                            <p>(k) intentionally or unintentionally violate any applicable local, state, national or international law, including, but not limited to, regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, including, without limitation, the New York Stock Exchange, the American Stock Exchange or the NASDAQ, and any regulations having the force of law;</p>
                            <p>(l) &quot;stalk&quot; or otherwise harass another; or</p>
                            <p>(m) collect or store personal data about other users.</p>
                            <p>(n) attempt to falsify traffic in order to earn revenue, not limited to using automated &apos;computer&apos; traffic, disguising traffic through anonymous proxy servers, &apos;hiding&apos; the Service through any method.</p>
                            <p>(o) register more than one account per person, except when one is a Publisher account and one is an Advertiser account. If a publisher is found to have referred themselves, the referral commission will be forfeited.</p>
                            <p>(p) offer any form of incentive to users who click on a&nbsp;<strong><?= $domain_name; ?></strong> link, not limited to points/bonus/money/gifts/traffic or link exchange.</p>You acknowledge that&nbsp;<strong><?= $domain_name; ?></strong> may OR MAY NOT pre-screen Content, but that&nbsp;<strong><?= $domain_name; ?></strong> shall have the right (but not the obligation) in their sole discretion to PRE-SCREEN, refuse, or move any Content (or Account) that is available via the Service. Without limiting the foregoing,&nbsp;<strong><?= $domain_name; ?></strong> and its designees shall have the right to remove any Content or Accounts that violates the TOS or is otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any Content or Accounts, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, you acknowledge that you may not rely on any Content or Accounts created by&nbsp;<strong><?= $domain_name; ?></strong> or submitted to&nbsp;<strong><?= $domain_name; ?></strong>, including without limitation information in&nbsp;<strong><?= $domain_name; ?></strong> message boards, and in all other parts of the Service. You acknowledge, consent and agree that&nbsp;<strong><?= $domain_name; ?></strong> may access, preserve, and disclose your account information and Content if required to do so by law or in a good faith belief that such access preservation or disclosure is reasonably necessary to:<p>(a) comply with legal process;</p>
                            <p>(b) enforce the TOS;</p>
                            <p>(c) respond to claims that any Content violates the rights of third parties;</p>
                            <p>(d) respond to your requests for customer service; or</p>
                            <p>(e) protect the rights, property, or personal safety of&nbsp;<strong><?= $domain_name; ?></strong>, its users, and the public.</p>You understand that the technical processing and transmission of the Service, including your Content, may involve<p>(a) transmissions over various networks; and</p>
                            <p>(b) changes to conform and adapt to technical requirements of connecting networks or devices.</p>You understand that the Service and software embodied within the Service may include security components that permit digital materials to be protected, and the use of these materials is subject to usage rules set by&nbsp;<strong><?= $domain_name; ?></strong> and/or content providers who provide content to the Service. You may not attempt to override or circumvent any of the usage rules embedded into the Service. Any unauthorized reproduction, publication, further distribution, or public exhibition of the materials provided on the Service, in whole or in part, is strictly prohibited.
                        </dd>
                        <dt><label>Submitted Content</label></dt>
                        <dd><strong><?= $domain_name; ?></strong> does not claim ownership of content or links you submit or make available for inclusion on the Service. However, with respect to content or links you submit or make available for inclusion on the Service, you grant&nbsp;<strong><?= $domain_name; ?></strong> the following worldwide, royalty-free and non-exclusive license(s) with respect to content or link you submit or make available for inclusion on&nbsp;<strong><?= $domain_name; ?></strong>, the license to use, distribute, reproduce, modify, adapt, publicly perform and publicly display such content or link on the Service solely for the purposes of providing and promoting the specific Service which such content or a link was submitted or made available. This license exists only for as long as you elect to continue to include such content or link on the Service and will terminate at the time you remove or&nbsp;<strong><?= $domain_name; ?></strong> removes such content or link from the Service.</dd>
                        <dt><label>User created Groups</label></dt>
                        <dd><strong><?= $domain_name; ?></strong> does not claim ownership of content or links that are submitted in the user created groups.&nbsp;<strong><?= $domain_name; ?></strong> shall not be liable for the conversation or content or any other media communicated in these groups.</dd>
                        <dt><label>Links and References</label></dt>
                        <dd>The Service may contain links to third-party websites or resources. Because&nbsp;<strong><?= $domain_name; ?></strong> has no control over such websites and resources, you acknowledge and agree that&nbsp;<strong><?= $domain_name; ?></strong> is not responsible or liable for:<p>(a) the availability or accuracy of such websites or resources; or</p>
                            <p>(b) the content, advertising, products, or services on or available from such websites or resources.</p>You further acknowledge and agree that&nbsp;<strong><?= $domain_name; ?></strong> shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods, or services available on or through any such website or resource.
                        </dd>
                        <dt><label>Termination</label></dt>
                        <dd>You agree that&nbsp;<strong><?= $domain_name; ?></strong>, in its sole discretion, may terminate, change or limit any of the Services or their availability to you, notice at any time and without prior notice, with or without cause. Further, you agree that&nbsp;<strong><?= $domain_name; ?></strong> shall not be liable to you or any third-party for any termination of your account, any associated email address, or access to the service.</dd>
                        <dt><label>Indeminity</label></dt>
                        <dd>You agree to indemnify and hold harmless&nbsp;<strong><?= $domain_name; ?></strong>, its parents, subsidiaries, affiliates, officers, agents, partners, and employees from any losses, expenses, damages, and costs, including reasonable attorney&apos;s fees, made by any third party due to or arising out of Content you submit, post, transmit or make available through the Service, your use of the Service, your connection to the Service, your violation of the Terms of use or your violation of any rights of another.</dd>
                        <dt><label>Disclaimer of Warranties</label></dt>
                        <dd>
                            <p>(a) YOU AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK AND ACKNOWLEDGE THAT THE SERVICES, INCLUDING, BUT NOT LIMITED TO, CONTENT, SERVICES, GOOD, OR ADVERTISEMENT ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS.&nbsp;<strong><?= $domain_name; ?></strong> DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, TITLE, OR FITNESS FOR A PARTICULAR PURPOSE OR USE.</p>
                            <p>(b)&nbsp;<strong><?= $domain_name; ?></strong> MAKES NO WARRANTY THAT (i) THE SERVICE WILL MEET YOUR REQUIREMENTS, (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED.</p>
                            <p>(c) ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.</p>
                            <p>(d) NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM&nbsp;<strong><?= $domain_name; ?></strong> OR THROUGH OR FROM THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TOS.</p>
                            <p>(e) A SMALL PERCENTAGE OF USERS MAY EXPERIENCE EPILEPTIC SEIZURES WHEN EXPOSED TO CERTAIN LIGHT PATTERNS OR BACKGROUND ON A COMPUTER SCREEN OR WHILE USING THE SERVICE. CERTAIN CONDITIONS MAY INDUCE PREVIOUSLY UNDETECTED EPILEPTIC SYMPTOMS EVEN IN USERS WHO HAVE NO HISTORY OF PRIOR SEIZURES OR EPILEPSY. IF YOU, OR ANYONE IN YOUR FAMILY, HAVE AN EPILEPTIC CONDITION, CONSULT YOUR PHYSICIAN PRIOR TO USING THE SERVICE. IMMEDIATELY DISCONTINUE USE OF THE SERVICE AND CONSULT YOUR PHYSICIAN IF YOU EXPERIENCE ANY OF THE FOLLOWING SYMPTOMS WHILE USING THE SERVICE -- DIZZINESS, ALTERED VISION, EYE OR MUSCLE TWITCHES, LOSS OF AWARENESS, DISORIENTATION, ANY INVOLUNTARY MOVEMENT, OR CONVULSIONS.</p>
                        </dd>
                        <dt><label>Limitation of Liabilities</label></dt>
                        <dd>
                            <p>(a) YOU UNDERSTAND AND AGREE THAT&nbsp;<strong><?= $domain_name; ?></strong> AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS, AND LICENSORS SHALL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF&nbsp;<strong><?= $domain_name; ?></strong> HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (v) ANY OTHER MATTER RELATING TO THE SERVICE.</p>
                            <p>(b) YOU UNDERSTAND AND AGREE THAT BY USING THE SERVICE, YOU MAY BE EXPOSED TO CONTENT THAT IS OFFENSIVE, INDECENT OR OBJECTIONABLE. UNDER NO CIRCUMSTANCES WILL&nbsp;<strong><?= $domain_name; ?></strong> AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS, AND LICENSORS BE LIABLE IN ANY WAY FOR ANY CONTENT, INCLUDING, BUT NOT LIMITED TO, ANY ERRORS OR OMISSIONS IN ANY CONTENT OR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, E-MAILED, TRANSMITTED OR OTHERWISE MADE AVAILABLE VIA THE SERVICE.</p>
                            <p>(c) YOU UNDERSTAND AND AGREE THAT THE SERVICE IS PROVIDED &quot;AS-IS&quot; AND THAT&nbsp;<strong><?= $domain_name; ?></strong> AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS, AND LICENSORS ASSUME NO RESPONSIBILITY FOR THE TIMELINESS, DELETION, MIS-DELIVERY OR FAILURE TO STORE ANY USER COMMUNICATIONS OR PERSONALIZATION SETTINGS.</p>
                        </dd>
                        <dt><label>Violations</label></dt>
                        <dd>Please report any violations of these <a href="<?= url("terms"); ?>"><strong><u>Term Of Service</u></strong></a> by using our &nbsp;<a href="<?= url("contact"); ?>"><strong><u>Contact Us</u></strong></a> form.</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>